% You are given two strings s a and t.
% String t is generated by random shuffling string s and then add one more
% letter at a random position.
% Return the letter that was added to t.

s = "abcd";
t = "abcde";
output = findTheDifference(s, t)

s = "";
t = "y";
output = findTheDifference(s, t)

s = "a";
t = "aa";
output = findTheDifference(s, t)

s = "ae";
t = "aea";
output = findTheDifference(s, t)